---
# Source: sonatype-nexus/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mynexus
  namespace: nexus-namespace
---
# Source: sonatype-nexus/templates/proxy-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mynexus
  namespace: nexus-namespace
  labels:
    app: sonatype-nexus
    fullname: mynexus
    chart: sonatype-nexus
    release: rclone-nexus
    heritage: Helm
spec:
  ports:
    - port: 8080
      name: mynexus
      protocol: TCP
      targetPort: 8080
  selector:
    app: sonatype-nexus
    release: rclone-nexus
  type: NodePort
---
# Source: sonatype-nexus/templates/deployment-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mynexus
  namespace: nexus-namespace
  labels:
    app: sonatype-nexus
    fullname: mynexus
    chart: sonatype-nexus
    release: rclone-nexus
    heritage: Helm
spec:
  replicas: 1
  serviceName: mynexus
  selector:
    matchLabels:
      app: sonatype-nexus
      release: rclone-nexus
  template:
    metadata:
      labels:
        app: sonatype-nexus
        release: rclone-nexus
    spec:
      serviceAccountName: mynexus
      containers:
        - name: nexus
          image: quay.io/travelaudience/docker-nexus:3.25.1
          imagePullPolicy: IfNotPresent
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:ActiveProcessorCount=4
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: "false"

          resources:
            {}
          ports:
            - containerPort: 5003
              name: nexus-docker-g
            - containerPort: 8081
              name: nexus-http
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 6
          volumeMounts:
            - mountPath: /nexus-data
              name: mynexus-data
        - name: nexus-proxy
          image: quay.io/travelaudience/docker-nexus-proxy:2.6.0
          resources:
            {}
          imagePullPolicy: IfNotPresent
          env:
            - name: ALLOWED_USER_AGENTS_ON_ROOT_REGEX
              value: "GoogleHC"
            - name: CLOUD_IAM_AUTH_ENABLED
              value: "false"
            - name: BIND_PORT
              value: "8080"
            - name: ENFORCE_HTTPS
              value: "false"
            - name: NEXUS_DOCKER_HOST
              value: 
            - name: NEXUS_HTTP_HOST
              value: 
            - name: UPSTREAM_DOCKER_PORT
              value: "5003"
            - name: UPSTREAM_HTTP_PORT
              value: "8081"
            - name: UPSTREAM_HOST
              value: "localhost"
          ports:
            - containerPort: 8080
              name: nexus-proxy
      securityContext:
        fsGroup: 200
      volumes:


## create pvc in case of statefulsets
  volumeClaimTemplates:
    - metadata:
        name: mynexus-data
        labels:
          app: sonatype-nexus
          fullname: mynexus
          chart: sonatype-nexus
          release: rclone-nexus
          heritage: Helm
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
    - metadata:
        name: mynexus-backup
        labels:
          app: sonatype-nexus
          fullname: mynexus
          chart: sonatype-nexus
          release: rclone-nexus
          heritage: Helm
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "8Gi"
    - metadata:
        name: mynexus-cloudiam
        labels:
          app: sonatype-nexus
          fullname: mynexus
          chart: sonatype-nexus
          release: rclone-nexus
          heritage: Helm
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Mi"
---
# Source: sonatype-nexus/templates/initpwd-job.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mynexus-initpwd-secret
  annotations:
    helm.sh/hook: "post-install"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
  labels:
    app: sonatype-nexus
    fullname: mynexus
    chart: sonatype-nexus
    release: rclone-nexus
    heritage: Helm
type: Opaque
data:
  nexusAuthorization: WVdSdGFXNDZZV1J0YVc0eE1qTT0=
  adminPassword: YWRtaW4zMjExMg==
---
# Source: sonatype-nexus/templates/initpwd-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: mynexus-initpwd-job
  annotations:
    helm.sh/hook: "post-install"
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    app: sonatype-nexus
    fullname: mynexus
    chart: sonatype-nexus
    release: rclone-nexus
    heritage: Helm
spec:
  backoffLimit: 5
  template:
    metadata:
      name: mynexus-initpwd
      labels:
        app: sonatype-nexus
        release: rclone-nexus
    spec:
      restartPolicy: Never
      containers:
        - name: nexus-initpwd
          image: curlimages/curl:7.73.0
          command:
            - /bin/sh
            - -ec
            - |
              curl --fail -X PUT \
                http://$(NEXUS_HOST)/service/rest/beta/security/users/admin/change-password \
                -H "Content-Type: text/plain" \
                -H "Authorization: Basic $(NEXUS_AUTHORIZATION)" \
                -d "$(ADMIN_PASSWORD)"
          env:
            - name: NEXUS_AUTHORIZATION
              valueFrom:
                secretKeyRef:
                  key: nexusAuthorization
                  name: mynexus-initpwd-secret
            - name: NEXUS_HOST
              value: mynexus.nexus-namespace:8081
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminPassword
                  name: mynexus-initpwd-secret
