apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-copy-plugins
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
data:
  copy_plugins.sh: |-
      #!/bin/bash
      {{- if .Values.plugins.deleteDefaultPlugins }}
      rm -f /opt/sonarqube/extensions/plugins/*.jar
      {{- end }}
      {{- if .Values.plugins.useDefaultPluginsPackage }}
      for f in /opt/sonarqube/extensions/plugins/tmp/*.jar
      do
        file=${f##*/} && file=${file%-[0-9]*}
        for original in /opt/sonarqube/extensions/plugins/*.jar
        do
          originalfile=${original##*/} && originalfile=${originalfile%-[0-9]*}
          if [ "$originalfile" = "$file" ]; then
            rm -f "$original"
          fi
        done
      done
      cp /opt/sonarqube/extensions/plugins/tmp/*.jar /opt/sonarqube/extensions/plugins/
      {{- end }}
      # set jdbc password env
      if [ -f /run/postgresql/secret/SONAR_JDBC_PASSWORD ]; then
        export SONAR_JDBC_PASSWORD=$(cat /run/postgresql/secret/SONAR_JDBC_PASSWORD)
      fi
      # start SonarQube
      /opt/sonarqube/docker/entrypoint.sh
