{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "sonarqube.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ .Values.ingress.labels | toYaml | trimSuffix "\n"| indent 4 -}}
{{- end}}
  annotations:
{{- if and $.Values.global.globalTLSSecretName .Values.ingress.hosts }}
    {{- $tlsSecrets := list -}}
    {{- range .Values.ingress.hosts }}
      {{- $noop := printf "%s=%s" .name $.Values.global.globalTLSSecretName -}}
      {{- $tlsSecrets = append $tlsSecrets $noop -}}
    {{- end }}
    alb.networking.{{ $.Values.global.labelBaseDomain }}/tls: {{ join "," $tlsSecrets | quote }}
{{- end }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
{{- if .Values.ingress.annotations}}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ printf "%s" .name }}
    http:
      paths:
      - backend:
          service:
            name: {{ default $serviceName .serviceName }}
            port:
              number: {{ default $servicePort .servicePort }}
        path: {{ .path}}
        pathType: {{ default "ImplementationSpecific" .pathType }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end }}
