{{- if .Values.initSysctl.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.initSysctl.serviceAccount.name }}
  name: {{ .Values.initSysctl.serviceAccount.name }}
{{- else  }}
  name: {{ include "sonarqube.fullname" . }}-initsysctl
{{- end }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end -}}
