apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-sonar-test-image
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^((/test-all)|(/test-image))"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |-
      target_branch.matches("^(main|release-.*|alauda-.*)$")
spec:
  pipelineRef:
    resolver: hub
    params:
    - name: catalog
      value: alauda
    - name: type
      value: tekton
    - name: kind
      value: pipeline
    - name: name
      value: clone-image-build-test-scan
    - name: version
      value: "0.2"

  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: git-revision
      value: "{{ source_branch }}"
    - name: git-commit
      value: "{{ revision }}"
    - name: git-version
      value: "0.1"
    

    - name: image-repository
      value: build-harbor.alauda.cn/devops/sonarqube-ce-test

    - name: dockerfile-path
      value: testing/Dockerfile
    
    - name: file-list-for-commit-sha
      value:
        - testing/

    - name: upstreams
      value:
      - |-
        repo-url: https://github.com/AlaudaDevops/devops-artifact.git
        branch-name: main
        yaml-file-path: ./values.yaml
    - name: upstream-branch-condition
      value: "^(main|master|release-.*|alauda-.*)$"
    - name: upstream-secret
      value: github-credentials
    - name: ignore-trivy-scan
      value: "true"

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: build-harbor.kauto.docfj
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: gitversion-config
      configMap:
        name: gitversion-config

  taskRunTemplate:
    podTemplate:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: "OnRootMismatch"
