apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sonarqube-integration-test
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^((/test-all)|(/integration-test)|(test-multi.*\ sonar-e2e.*))$"
    pipelinesascode.tekton.dev/on-cel-expression: |-
      (
        source_branch.matches("^(main|release-.*|alauda.*)$")
      ) && (
        "charts/sonarqube/***".pathChanged() ||
        ".tekton/integration.yaml".pathChanged()
      ) && ((
        event == "push" && (
          source_branch.matches("^(main|release-.*|alauda.*)$") ||
          target_branch.matches("^(main|release-.*|alauda.*)$") ||
          target_branch.startsWith("refs/tags/")
        )
      ))
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  taskRunSpecs:
    - pipelineTaskName: run-test
      computeResources:
        limits:
          cpu: "4"
          memory: 4Gi
  timeouts:
    pipeline: 5h
    tasks: 5h
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: alauda
      - name: type
        value: tekton
      - name: kind
        value: pipeline
      - name: name
        value: vcluster-integration-test
      - name: version
        value: "0.1"

  params:
    - name: git-revision
      value:
        url: "{{ repo_url }}"
        branch: "{{ source_branch }}"
        commit: "{{ revision }}"
    - name: test
      value:
        image: build-harbor.alauda.cn/devops/sonarqube-ce-test:v2025.1.0-v0.1.0-testartcaseid.1019.ge7e60a1-e7e60a
        command: |
          set -x
          export KUBECONFIG=$(workspaces.config.path)/vcluster-config
          kubectl config view

          trap 'chmod -R a+r allure-results/* && mkdir -p $(workspaces.source.path)/testing/allure-results && cp -r allure-results/* $(workspaces.source.path)/testing/allure-results/' EXIT
          echo "run integration tests..."
          export REPORT=allure
          export TAGS='@sonarqube-chart-deploy'
          make test
    - name: vcluster
      value:
        custom-config: |
          sync:
            toHost:
              ingresses:
                enabled: true
            fromHost:
              storageClasses:
                enabled: true
              ingressClasses:
                enabled: true
    - name: report
      value:
        command: |
          cd $(workspaces.source.path)/testing
          allure generate --clean

          echo "Listing contents of report directory"
          ls -al
        path: testing/allure-report
  workspaces:
    - name: kube-config
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 50Mi
    - name: cache
      persistentVolumeClaim:
        claimName: build-cache
      subPath: golang
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
    - name: upload-conf
      secret:
        secretName: upload-allure-report-conf
